- name: Execute a script on the target VM
  hosts: ec2-54-172-19-222.compute-1.amazonaws.com
  tasks:
    - name: Ping the Windows host
      win_ping:
      register: ping_result

    - name: Display ping result
      debug:
        msg: "{{ ping_result }}"

    - name: Run the script
      win_shell: C:\Users\Administrator\Desktop\windowspasswordexpiry.ps1
      register: script_result

    - name: Display script output
      debug:
        msg: "{{ script_result.stdout }}"