---
- name: Execute script on Linux or Windows VM
  hosts: all  # Will auto-detect OS type via group
  gather_facts: no

  tasks:
    # -- Windows Tasks --
    - name: Ping Windows host
      win_ping:
      when: "'oswindows' in group_names"
      register: win_ping

    - name: Display Windows ping result
      debug:
        msg: "{{ win_ping }}"
      when: "'oswindows' in group_names"
