- name: Execute script on Linux or Windows VM
  hosts: all
  gather_facts: no

  tasks:
    # -- Windows Tasks --
    - name: Ping Windows host
      ansible.windows.win_ping:
      when: "'oswindows' in group_names"

    - name: Copy script to the Administrator's desktop
      ansible.windows.win_copy:
        src: windowspasswordexpiry.ps1
        dest: C:\Users\Administrator\Desktop\windowspasswordexpiry.ps1
      when: "'oswindows' in group_names"

    - name: Run the PowerShell script
      ansible.windows.win_shell:
        command: C:\Users\Administrator\Desktop\windowspasswordexpiry.ps1
      register: script_result
      when: "'oswindows' in group_names"

    - name: Display script output
      ansible.builtin.debug:
        msg: "{{ script_result.stdout_lines }}"
      when: "'oswindows' in group_names"
